name: Cassette Merge

# only trigger on pull request closed events
on:
  pull_request_target:
    types: [ closed ]

jobs:
  merge:
    runs-on: ubuntu-latest
    environment: cassette-merge
    steps:
      - uses: OjusWiZard/action-cassette-deck@main
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          cassette_repo: test-caching